#!/usr/bin/env python3
"""Tests for bundled extension manifest handling."""

import json
import os
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from typing import cast
from unittest.mock import MagicMock, patch

from bos_build.core.context import Context
from bos_build.core.products import (
    BROWSEROS_AGENT_EXTENSION_ID,
    BROWSEROS_BUG_REPORTER_EXTENSION_ID,
    BROWSERCLAW_EXTENSION_ID,
)
from bos_build.core.products import get_product_descriptor
from bos_build.core.step import ValidationError
from bos_build.release.extensions.specs import spec_by_name
from bos_build.steps.extensions.bundled_extensions import (
    BundledExtensionsModule,
    ExtensionInfo,
    LocalBundle,
    ManifestBundle,
)

CLAW_EXTENSION_ID = "pjimfkbpehlcllblajnpfamdfjhhlgkc"
MODULE = "bos_build.steps.extensions.bundled_extensions"


class BundledExtensionsManifestTest(unittest.TestCase):
    def test_bundled_manifest_staging_file_is_coherent(self) -> None:
        # Structural check only: the file is regenerated by
        # `browseros release extensions`, so exact versions must not be pinned.
        repo_root = Path(__file__).resolve().parents[5]
        manifest_path = repo_root / "updates" / "extensions" / "bundled-manifest.xml"

        extensions = BundledExtensionsModule()._parse_manifest_xml(
            manifest_path.read_text()
        )

        by_id = {ext.id: ext for ext in extensions}
        required = get_product_descriptor("browseros").required_extension_ids
        for extension_id, name in required:
            self.assertIn(extension_id, by_id, name)

        for ext in extensions:
            self.assertRegex(
                ext.codebase,
                r"^https://cdn\.browseros\.com/extensions/[a-z]+-[0-9.]+\.crx$",
            )
            self.assertTrue(ext.version)
            self.assertIn(f"-{ext.version}.crx", ext.codebase)

    def test_required_ids_cover_agent_bug_reporter_and_claw(self) -> None:
        # Both products bundle all three until the chromium-side fix lands
        # (see the required_extension_ids TODO in common/products.py).
        expected = {
            "adlpneommgkgeanpaekgoaolcpncohkf": "BrowserOS bug reporter",
            "bflpfmnmnokmjhmgnolecpppdbdophmk": "BrowserOS agent",
            CLAW_EXTENSION_ID: "BrowserClaw app",
        }
        self.assertEqual(
            dict(get_product_descriptor("browseros").required_extension_ids),
            expected,
        )
        self.assertEqual(
            dict(get_product_descriptor("browserclaw").required_extension_ids),
            expected,
        )

    def test_generated_json_maps_claw_id_to_crx(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            BundledExtensionsModule()._generate_json(
                [
                    ExtensionInfo(
                        id=CLAW_EXTENSION_ID,
                        version="0.0.1",
                        codebase=(
                            "https://cdn.browseros.com/extensions/browserclaw-0.0.1.crx"
                        ),
                    )
                ],
                output_dir,
            )

            data = json.loads((output_dir / "bundled_extensions.json").read_text())

        self.assertEqual(
            data[CLAW_EXTENSION_ID],
            {
                "external_crx": f"{CLAW_EXTENSION_ID}.crx",
                "external_version": "0.0.1",
            },
        )

    def test_missing_claw_app_fails_validation(self) -> None:
        extensions = [
            ExtensionInfo(
                id="adlpneommgkgeanpaekgoaolcpncohkf",
                version="52.0.0.0",
                codebase="https://cdn.browseros.com/extensions/bugreporter.crx",
            ),
            ExtensionInfo(
                id="bflpfmnmnokmjhmgnolecpppdbdophmk",
                version="0.0.115.0",
                codebase="https://cdn.browseros.com/extensions/agent.crx",
            ),
        ]

        with self.assertRaisesRegex(
            RuntimeError,
            f"BrowserClaw app \\({CLAW_EXTENSION_ID}\\)",
        ):
            BundledExtensionsModule()._validate_required_extensions(
                extensions, self._ctx("browserclaw")
            )

    def test_browserclaw_selects_all_required_extensions(self) -> None:
        extensions = [
            ExtensionInfo(
                id="adlpneommgkgeanpaekgoaolcpncohkf",
                version="52.0.0.0",
                codebase="https://cdn.browseros.com/extensions/bugreporter.crx",
            ),
            ExtensionInfo(
                id="bflpfmnmnokmjhmgnolecpppdbdophmk",
                version="0.0.115.0",
                codebase="https://cdn.browseros.com/extensions/agent.crx",
            ),
            ExtensionInfo(
                id=CLAW_EXTENSION_ID,
                version="0.0.1",
                codebase="https://cdn.browseros.com/extensions/browserclaw.crx",
            ),
        ]

        selected = BundledExtensionsModule()._select_product_extensions(
            extensions, self._ctx("browserclaw")
        )

        # All three ship for browserclaw too while the packaging TODO stands.
        self.assertEqual(
            [ext.id for ext in selected],
            [
                "adlpneommgkgeanpaekgoaolcpncohkf",
                "bflpfmnmnokmjhmgnolecpppdbdophmk",
                CLAW_EXTENSION_ID,
            ],
        )

    def test_hybrid_mode_builds_in_repo_and_downloads_external_required(self) -> None:
        plan = BundledExtensionsModule()._plan_hybrid_bundles(
            [
                ExtensionInfo(
                    id=BROWSEROS_BUG_REPORTER_EXTENSION_ID,
                    version="52.0.0.0",
                    codebase="https://cdn.browseros.com/extensions/bugreporter.crx",
                ),
                # Local-buildable IDs may still appear in the manifest; local wins.
                ExtensionInfo(
                    id=BROWSEROS_AGENT_EXTENSION_ID,
                    version="0.0.115.0",
                    codebase="https://cdn.browseros.com/extensions/agent.crx",
                ),
                ExtensionInfo(
                    id=BROWSERCLAW_EXTENSION_ID,
                    version="0.0.1",
                    codebase="https://cdn.browseros.com/extensions/browserclaw.crx",
                ),
            ],
            self._ctx("browseros", bundle_local_extensions=True),
        )

        self.assertIsInstance(plan[0], ManifestBundle)
        self.assertIsInstance(plan[1], LocalBundle)
        self.assertIsInstance(plan[2], LocalBundle)
        self.assertEqual(
            cast(ManifestBundle, plan[0]).extension.id,
            BROWSEROS_BUG_REPORTER_EXTENSION_ID,
        )
        self.assertEqual(cast(LocalBundle, plan[1]).spec.name, "agent")
        self.assertEqual(cast(LocalBundle, plan[2]).spec.name, "browserclaw")

    def test_hybrid_mode_fails_when_external_required_missing(self) -> None:
        with self.assertRaisesRegex(RuntimeError, "BrowserOS bug reporter"):
            BundledExtensionsModule()._plan_hybrid_bundles(
                [
                    ExtensionInfo(
                        id=BROWSEROS_AGENT_EXTENSION_ID,
                        version="0.0.115.0",
                        codebase="https://cdn.browseros.com/extensions/agent.crx",
                    ),
                    ExtensionInfo(
                        id=BROWSERCLAW_EXTENSION_ID,
                        version="0.0.1",
                        codebase="https://cdn.browseros.com/extensions/browserclaw.crx",
                    ),
                ],
                self._ctx("browseros", bundle_local_extensions=True),
            )

    def test_build_local_extension_uses_spec_recipe_without_version_stamp(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            package_root = root / "repo" / "packages" / "browseros"
            source_root = root / "repo" / "packages" / "browseros-agent"
            manifest = source_root / "apps" / "app" / "package.json"
            manifest.parent.mkdir(parents=True)
            manifest.write_text(json.dumps({"version": "0.0.123"}))
            output_dir = root / "chromium" / "bundled_extensions"
            output_dir.mkdir(parents=True)
            ctx = cast(Context, SimpleNamespace(root_dir=package_root))

            patches = {
                "resolve_source": MagicMock(return_value=source_root),
                "write_env_file": MagicMock(),
                "run_command": MagicMock(),
                "pack_crx": MagicMock(),
            }
            with (
                patch.dict(os.environ, {"BROWSEROS_AGENT_V2_KEY": "agent-pem"}),
                patch(f"{MODULE}.resolve_source", patches["resolve_source"]),
                patch(f"{MODULE}.write_env_file", patches["write_env_file"]),
                patch(f"{MODULE}.run_command", patches["run_command"]),
                patch(f"{MODULE}.pack_crx", patches["pack_crx"]),
            ):
                info = BundledExtensionsModule()._build_and_pack_local_extension(
                    spec_by_name("agent"), ctx, output_dir, "chrome-bin"
                )

        self.assertEqual(info.id, BROWSEROS_AGENT_EXTENSION_ID)
        self.assertEqual(info.version, "0.0.123")
        patches["resolve_source"].assert_called_once()
        commands = [call.args for call in patches["run_command"].call_args_list]
        self.assertEqual(
            commands,
            [
                ("bun ci", source_root),
                ("bun run build:agent", source_root),
            ],
        )
        pack_args = patches["pack_crx"].call_args.args
        self.assertEqual(pack_args[0], source_root / "apps/app/dist/chrome-mv3")
        self.assertEqual(pack_args[1], "agent-pem")
        self.assertEqual(pack_args[2], "chrome-bin")
        self.assertEqual(
            pack_args[3],
            output_dir / f"{BROWSEROS_AGENT_EXTENSION_ID}.crx",
        )

    def test_local_mode_preflight_requires_only_local_signing_keys(self) -> None:
        with (
            patch.dict(
                os.environ,
                {
                    "BROWSEROS_AGENT_V2_KEY": "agent-pem",
                    "BROWSERCLAW_KEY": "claw-pem",
                },
                clear=False,
            ),
            patch(f"{MODULE}.find_chrome_binary", return_value="chrome-bin"),
        ):
            BundledExtensionsModule().preflight(
                self._ctx("browseros", bundle_local_extensions=True)
            )

    def test_local_mode_preflight_names_missing_local_signing_key(self) -> None:
        env = {
            k: v
            for k, v in os.environ.items()
            if k not in ("BROWSEROS_AGENT_V2_KEY", "BROWSERCLAW_KEY")
        }
        with (
            patch.dict(os.environ, env, clear=True),
            patch(f"{MODULE}.find_chrome_binary", return_value="chrome-bin"),
            self.assertRaisesRegex(ValidationError, "BROWSEROS_AGENT_V2_KEY"),
        ):
            BundledExtensionsModule().preflight(
                self._ctx("browseros", bundle_local_extensions=True)
            )

    def _ctx(
        self,
        product: str,
        bundle_local_extensions: bool = False,
        root_dir: Path | None = None,
    ):
        return cast(
            Context,
            SimpleNamespace(
                product=get_product_descriptor(product),
                bundle_local_extensions=bundle_local_extensions,
                root_dir=root_dir or Path("/repo/packages/browseros"),
            ),
        )


if __name__ == "__main__":
    unittest.main()
